on:
  - workflow_dispatch
  - push

name: CI


jobs:
  test:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: "8"

      - name: Build and Release
        run: ./gradlew clean check
  test_node:
    name: Build npm package

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: "8"

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Build npm package
        working-directory: node/rmf-codegen
        run: yarn build && npx rmf-codegen
