on:
  - workflow_dispatch

name: SigningTest

jobs:
  sign:
    name: Build and release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: tools/setup-signing-key.sh
