on:
  - workflow_dispatch

name: SigningTest

jobs:
  sign:
    name: Build and release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: scripts/setup-signing-key.sh
        env:
          DECRYPTER: ${{ secrects.DECRYPTER }}
          SIGNING_KEY: ${{ secrects.SIGNING_KEY }}
          PASSPHRASE: ${{ secrects.PASSPHRASE }}
